# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "mutest-driver"
version = "0.0.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
mutest-emit = { path = "../mutest-emit" }
mutest-operators = { path = "../mutest-operators" }
mutest-runtime = { path = "../mutest-runtime" }

clap = { version = "4", features = ["cargo"] }

rand = { version = "0.8", optional = true }
rand_seeder = { version = "0.2", optional = true }

[features]
default = ["random"]
random = ["mutest-emit/random", "dep:rand", "dep:rand_seeder"]
